name: 🚀 Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🏗️ Build & 🛰️ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 📦 Install dependencies
        run: npm install --legacy-peer-deps

      - name: 🏗️ Build Astro
        run: npm run build

      - name: 📂 Deploy via FTP
        uses: AykutSarac/ftp-deploy@v1.0.2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./dist/
          # Zmieniamy na './' - to oznacza, że robot po zalogowaniu 
          # ma wrzucić pliki bezpośrednio tam, gdzie się znajduje,
          # bez tworzenia dodatkowych folderów.
          remoteDir: ./public_html/
          forcePassive: true
